# -*- coding: utf-8 -*-
"""02입력문.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H5qyUCZSq3VdSSLbXGjhtinkSJV1a3C1
"""

#입력문
input('이름을 입력하세요')

#입력받아 변수에 저장
name = input('이름을 입력하세요')
print('안녕하세요 %s님 만나서 반갑습니다.' %name)

#입력 - 서식지정
print("%10s" %"Python")   #10칸의 너비에 오른쪽 정렬
print("%-10s" %"Python")  #10칸의 너비에 왼쪽 정렬

#값을 입력 받아 숫자 변수에 저장
num = int(input('원의 지름을 입력하세요'))
result = num * 3.14
print('원의 둘레는 %.2f입니다.' %result)   #정수 출력

#입력 - format 지정 파이썬3부터는 format() 메소드를 사용한 문자열 권장 인덱스 생략 가능
이름 = '김작가'
나이 = 25
직업 = "작사 작곡가"

소개 = "안녕하세요 저는 {}입니다. {}살이고, {}로 활동하고 있습니다." .format(이름, 나이, 직업)
print(소개)